# Comparison of Two Time Series of Maps 1.0
*This notebook implements the framework from the article “Foundational concepts and equations to compare two time series of maps” to quantify and visualize agreement and change between two temporal map series. Using toy data, it defines modular Python functions to compute presence‐agreement components, gains and losses, and full‐extent change metrics, and produces clear visualizations and exportable results for reproducible analysis.*

## Table of Contents  
1. [Environment Setup](#environment-setup)
2. [Toy Data Input Format](#data-preparation)
3. [Presence Agreement Components (Eqs 1–12)](#presence-agreement)
4. [Change Components: Gains & Losses (Eqs 13–28)](#change-components)
5. [Full-Extent Change Metrics (Eqs 29–40, 41–52)](#full-extent)
6. [Visualization of Results](#visualization)
7. [Exporting Results](#export)


## 1. Environment Setup <a id="environment-setup"></a>

### 1.1 Install Dependencies  

In [ ]:
# Install packages needed for:
# - numeric arrays and fast math (numpy)
# - tabular data manipulation (pandas)
# - plotting charts and graphs (matplotlib)
# - reading and writing raster map files (rasterio)
# - handling multi-dimensional map arrays with geospatial coordinates (xarray, rioxarray)
# - exporting tables to Excel (openpyxl)
# - showing progress bars in long loops (tqdm)
%pip install numpy pandas matplotlib rasterio xarray rioxarray openpyxl tqdm 

### 1.2 Import Libraries  

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import rasterio
from rasterio.transform import from_origin
import xarray as xr
import rioxarray
from tqdm import tqdm
import openpyxl
import os

### 1.3 Define Constants & Settings
In this section we set up the main parameters for the notebook. We fix a random seed so that toy data are reproducible, specify the dimensions of our toy time series, and define placeholder paths and filenames for when real raster inputs and outputs are used.

In [ ]:
# Directories
input_dir = r"C:\Users\AntFonseca\github\compare-time-series\input"
output_dir = r"C:\Users\AntFonseca\github\compare-time-series\output"

# Output filenams
metrics_excel = "presence_change_metrics.xlsx"

## 2. Toy Data Input Format <a id="data-preparation"></a>

### 2.1 Generate or Load Toy Time Series Array
In this section we build the toy data arrays exactly as in the article example.

In [ ]:
# Dimensions matching the article’s toy example
num_time_points = 3   # number of time points
num_pixels = 2        # number of pixels in each snapshot

# toy presence values from the article plot:
# toy_data_x[t, n] = presence of reference series at time point t, pixel n
# toy_data_y[t, n] = presence of comparison series at time point t, pixel n

toy_data_x = np.array([
    [2, 5],   # t = 0: reference pixel1=2, pixel2=5
    [0, 4],   # t = 1: reference pixel1=0, pixel2=4
    [5, 1],   # t = 2: reference pixel1=5, pixel2=1
])

toy_data_y = np.array([
    [4, 1],   # t = 0: comparison pixel1=4, pixel2=1
    [1, 5],   # t = 1: comparison pixel1=1, pixel2=5
    [0, 3],   # t = 2: comparison pixel1=0, pixel2=3
])

### 2.2 Export Toy Data as Raster Files

Here we write each map layer of our toy arrays to single‐band GeoTIFFs in the input folder. These rasters will later be read back in exactly like real map inputs.

In [ ]:
# Ensure input directory exists
os.makedirs(input_dir, exist_ok=True)

# Raster metadata for a 1×num_pixels image, without CRS
height = 1
width = num_pixels
transform = from_origin(0, num_pixels, 1, 1)  # top‐left corner at (0, num_pixels), pixel size = 1×1
meta = {
    "driver": "GTiff",
    "height": height,
    "width": width,
    "count": 1,
    "dtype": toy_data_x.dtype,
    "transform": transform
}

# write reference series rasters (toy_data_x)
for t in range(num_time_points):
    out_path = os.path.join(input_dir, f"toy_data_x_time{t}.tif")
    with rasterio.open(out_path, "w", **meta) as dst:
        dst.write(toy_data_x[t][np.newaxis, :], 1)

# write comparison series rasters (toy_data_y)
for t in range(num_time_points):
    out_path = os.path.join(input_dir, f"toy_data_y_time{t}.tif")
    with rasterio.open(out_path, "w", **meta) as dst:
        dst.write(toy_data_y[t][np.newaxis, :], 1)


## 3. Presence Agreement Components (Eqs 1–12) <a id="presence-agreement"></a>
In this section we compute the core presence‐agreement metrics—hits, misses, false alarms, spatial differences, and temporal differences—for each pixel at each time point, following Equations 1–12 of the article.

### 3.1 Define Presence Variables:

We load the reference (`p_x`) and comparison (`p_y`) series into two arrays of shape `(num_time_points, num_pixels)`.  
Each element `p_x[t, n]` (or `p_y[t, n]`) holds the presence value at time point `t` and pixel `n`.

In [ ]:
# Gather and sort the toy-data raster filenames
x_files = sorted([
    os.path.join(input_dir, f)
    for f in os.listdir(input_dir)
    if f.startswith("toy_data_x_time")
])
y_files = sorted([
    os.path.join(input_dir, f)
    for f in os.listdir(input_dir)
    if f.startswith("toy_data_y_time")
])

# Initialize presence arrays
p_x = np.zeros((num_time_points, num_pixels), dtype=toy_data_x.dtype)
p_y = np.zeros((num_time_points, num_pixels), dtype=toy_data_y.dtype)

# Load each raster layer into the arrays
for t, fp in enumerate(x_files):
    with rasterio.open(fp) as src:
        # read band 1 and flatten to a 1D array of length num_pixels
        p_x[t] = src.read(1).flatten()

for t, fp in enumerate(y_files):
    with rasterio.open(fp) as src:
        p_y[t] = src.read(1).flatten()

# Print to console for verification
print("Loaded reference presence (p_x):")
print(p_x)
print("\nLoaded comparison presence (p_y):")
print(p_y)

Loaded reference presence (p_x):
[[2 5]
 [0 4]
 [5 1]]

Loaded comparison presence (p_y):
[[4 1]
 [1 5]
 [0 3]]


### 3.2 Implement Hit, Miss, False Alarm, Spatial Difference, and Temporal Difference Functions
In this subsection we define five functions that implement Equations 1–12 for presence at each time point and pixel:
- **hit(px, py):** amount of shared presence  
- **miss(px, py):** amount of reference-only presence  
- **false_alarm(px, py):** amount of comparison-only presence  
- **spatial_diff(px, py):** difference in magnitude when both series have presence  
- **temporal_diff(px_prev, px, py_prev, py):** timing differences across consecutive time points  

Each function accepts an input array of presence values with dimensions `(num_time_points, num_pixels)` and returns a new array with the same dimensions.

In [24]:
def hit(px, py):
    """
    Presence hit: shared presence at each time point and pixel.
    h[t, n] = min(px[t, n], py[t, n])
    """
    return np.minimum(px, py)

def miss(px, py):
    """
    Presence miss: reference-only presence.
    m[t, n] = max(px[t, n] - py[t, n], 0)
    """
    return np.clip(px - py, a_min=0, a_max=None)

def false_alarm(px, py):
    """
    Presence false alarm: comparison-only presence.
    f[t, n] = max(py[t, n] - px[t, n], 0)
    """
    return np.clip(py - px, a_min=0, a_max=None)

def spatial_diff(px, py):
    """
    Spatial difference: magnitude difference when both have presence.
    u[t, n] = abs(px[t, n] - py[t, n]) where both px and py > 0, else 0.
    """
    diff = np.abs(px - py)
    mask = (px > 0) & (py > 0)
    return diff * mask

def temporal_diff(px_prev, px, py_prev, py):
    """
    Temporal difference: presence shifts between consecutive time points.
    v[t, n] = abs((px[t, n] - px_prev[t, n]) - (py[t, n] - py_prev[t, n]))
    for t = 1..T, zero for t = 0.
    """
    # pad first time point with zeros
    delta_x = px - px_prev
    delta_y = py - py_prev
    td = np.abs(delta_x - delta_y)
    td[0, :] = 0
    return td


### 3.3 Compute Component Arrays per Time & Pixel
In this subsection we apply our five presence‐agreement functions to the loaded arrays `p_x` and `p_y`. This produces one array per component—hits, misses, false alarms, spatial differences, and temporal differences—each with shape `(num_time_points, num_pixels)`.

In [25]:
# Compute presence‐agreement components
h = hit(p_x, p_y)
m = miss(p_x, p_y)
f = false_alarm(p_x, p_y)
u = spatial_diff(p_x, p_y)

# For temporal differences, build “previous” arrays by shifting and padding with zeros
px_prev = np.vstack([np.zeros((1, num_pixels), dtype=p_x.dtype), p_x[:-1]])
py_prev = np.vstack([np.zeros((1, num_pixels), dtype=p_y.dtype), p_y[:-1]])
v = temporal_diff(px_prev, p_x, py_prev, p_y)

# Verify shapes and sample values
print("hits (h):\n", h)
print("misses (m):\n", m)
print("false alarms (f):\n", f)
print("spatial diffs (u):\n", u)
print("temporal diffs (v):\n", v)


hits (h):
 [[2 1]
 [0 4]
 [0 1]]
misses (m):
 [[0 4]
 [0 0]
 [5 0]]
false alarms (f):
 [[2 0]
 [1 1]
 [0 2]]
spatial diffs (u):
 [[2 4]
 [0 1]
 [0 2]]
temporal diffs (v):
 [[0 0]
 [1 5]
 [6 1]]


### 3.4 Aggregate Presence Components
In this step we combine the per-pixel components into summary metrics:

- **Spatial aggregates** (one value per time point \(t\)):  
  - `H_t`: total shared presence across all pixels at time `t`  
  - `M_t`: total reference-only presence across all pixels at time `t`  
  - `F_t`: total comparison-only presence across all pixels at time `t`  
  - `U_t`: total spatial difference across all pixels at time `t`  
  - `V_t`: total temporal difference across all pixels at time `t`  

- **Temporal aggregates** (one value per pixel `n`):  
  - `H_n`: total shared presence for pixel `n` across all time points  
  - `M_n`: total reference-only presence for pixel `n` across all time points  
  - `F_n`: total comparison-only presence for pixel `n` across all time points  
  - `U_n`: total spatial difference for pixel `n` across all time points  
  - `V_n`: total temporal difference for pixel `n` across all time points  

The code below computes these arrays and prints them for verification.

In [26]:
# Spatial aggregates per time point (axis=1 sums over pixels)
H_t = h.sum(axis=1)
M_t = m.sum(axis=1)
F_t = f.sum(axis=1)
U_t = u.sum(axis=1)
V_t = v.sum(axis=1)

# Temporal aggregates per pixel (axis=0 sums over time points)
H_n = h.sum(axis=0)
M_n = m.sum(axis=0)
F_n = f.sum(axis=0)
U_n = u.sum(axis=0)
V_n = v.sum(axis=0)

# Print results for verification
print("Spatial aggregates at each time point:")
print("H_t, M_t, F_t, U_t, V_t =", H_t, M_t, F_t, U_t, V_t)

print("\nTemporal aggregates for each pixel:")
print("H_n, M_n, F_n, U_n, V_n =", H_n, M_n, F_n, U_n, V_n)


Spatial aggregates at each time point:
H_t, M_t, F_t, U_t, V_t = [3 4 1] [4 0 5] [2 2 2] [6 1 2] [0 6 7]

Temporal aggregates for each pixel:
H_n, M_n, F_n, U_n, V_n = [2 6] [5 4] [3 3] [2 7] [7 6]


## 4. Change Components: Gains & Losses (Eqs 13–28) <a id="change-components"></a>
In this section we quantify change between consecutive time points by decomposing it into **gains** (positive increases) and **losses** (negative decreases) for both series. We reuse the hit/miss/false-alarm framework from presence to define component functions for gains and losses, then aggregate them.

### 4.1 Define Gain & Loss Variables:
Load or compute the per-interval gain arrays `g_x`, `g_y` and loss arrays `l_x`, `l_y` from the raw presence data.

### 4.2 Implement Gain-Component Functions
Define functions that calculate gain hits, gain misses, gain false alarms, spatial differences, and temporal differences by substituting presence (`p`) with gains (`g`).


### 4.3 Implement Loss-Component Functions
Similarly, define loss hits, loss misses, loss false alarms, spatial differences, and temporal differences by substituting presence (`p`) with losses (`l`).

### 4.4 Aggregate Gain & Loss Components
Sum each gain and loss component across pixels (for each interval) and across intervals (for each pixel) to create summary change metrics.

## 5. Full-Extent Change Metrics (Eqs 29–40, 41–52) <a id="full-extent"></a>

### 5.1 Compute Total Gains & Losses over \(t=0\to T\)  

### 5.2 Quantity Metrics (Interval & Full-Extent Sums)  

### 5.3 Pixel-Wise Summary Metrics  

## 6. Visualization of Results <a id="visualization"></a>

### 6.1 Stacked Bar Chart: Presence Agreement  

### 6.2 Stacked Bar Chart: Gain & Loss Components  

### 6.3 Composition of Full-Extent Change  

## 7. Exporting Results <a id="export"></a>

### 7.1 Save Metrics DataFrame to CSV/Excel  

### 7.2 Save Figures (PNG)  